<a href="https://colab.research.google.com/github/ManjunathD620/Cancer-Detection-using-deep-learaning/blob/main/Cancer_Detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

data = pd.read_csv("/content/data.csv")
data.head()

         id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [ ]:
data = data.replace({"diagnosis": {'M': 0, 'B': 1}})
data = data.iloc[:, :-20]
x = data.drop("diagnosis" ,axis=1).values
y = data["diagnosis"].values
print(x.shape)
print(y.shape)

(569, 12)
(569,)

In [ ]:
data.head()

         id  diagnosis  ...  fractal_dimension_mean  radius_se
0    842302          0  ...                 0.07871     1.0950
1    842517          0  ...                 0.05667     0.5435
2  84300903          0  ...                 0.05999     0.7456
3  84348301          0  ...                 0.09744     0.4956
4  84358402          0  ...                 0.05883     0.7572

[5 rows x 13 columns]

In [ ]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.30, random_state=10)

In [ ]:
from keras.models import Sequential
from keras.layers import Dense

model = Sequential()
model.add(Dense(1000, input_dim=12, activation="relu"))
model.add(Dense(500, activation="relu"))
model.add(Dense(300, activation="relu"))
model.add(Dense(100, activation="relu"))
model.add(Dense(12, activation="relu"))
model.add(Dense(1, activation="sigmoid"))

model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [ ]:
model.fit(x_train,y_train, epochs=20, batch_size=10,validation_data=(x_test,y_test))

Epoch 1/20
40/40 [==============================] - 1s 16ms/step - loss: 246259.7656 - accuracy: 0.4749 - val_loss: 12993.6680 - val_accuracy: 0.6550
Epoch 2/20
40/40 [==============================] - 0s 11ms/step - loss: 99577.7266 - accuracy: 0.5201 - val_loss: 180508.1719 - val_accuracy: 0.3450
Epoch 3/20
40/40 [==============================] - 1s 13ms/step - loss: 11182.9414 - accuracy: 0.5553 - val_loss: 0.6872 - val_accuracy: 0.6550
Epoch 4/20
40/40 [==============================] - 0s 12ms/step - loss: 0.6883 - accuracy: 0.6156 - val_loss: 0.6859 - val_accuracy: 0.6550
Epoch 5/20
40/40 [==============================] - 1s 13ms/step - loss: 0.6873 - accuracy: 0.6156 - val_loss: 0.6843 - val_accuracy: 0.6550
Epoch 6/20
40/40 [==============================] - 0s 12ms/step - loss: 0.6862 - accuracy: 0.6156 - val_loss: 0.6830 - val_accuracy: 0.6550
Epoch 7/20
40/40 [==============================] - 0s 9ms/step - loss: 0.6851 - accuracy: 0.6156 - val_loss: 0.6815 - val_accuracy: 0.6550
Epoch 8/20
40/40 [==============================] - 0s 10ms/step - loss: 0.6841 - accuracy: 0.6156 - val_loss: 0.6797 - val_accuracy: 0.6550
Epoch 9/20
40/40 [==============================] - 0s 9ms/step - loss: 0.6830 - accuracy: 0.6156 - val_loss: 0.6781 - val_accuracy: 0.6550
Epoch 10/20
40/40 [==============================] - 0s 9ms/step - loss: 0.6819 - accuracy: 0.6156 - val_loss: 0.6766 - val_accuracy: 0.6550
Epoch 11/20
40/40 [==============================] - 0s 9ms/step - loss: 0.6809 - accuracy: 0.6156 - val_loss: 0.6751 - val_accuracy: 0.6550
Epoch 12/20
40/40 [==============================] - 1s 13ms/step - loss: 0.6799 - accuracy: 0.6156 - val_loss: 0.6739 - val_accuracy: 0.6550
Epoch 13/20
40/40 [==============================] - 0s 11ms/step - loss: 0.6789 - accuracy: 0.6156 - val_loss: 0.6724 - val_accuracy: 0.6550
Epoch 14/20
40/40 [==============================] - 0s 11ms/step - loss: 0.6780 - accuracy: 0.6156 - val_loss: 0.6711 - val_accuracy: 0.6550
Epoch 15/20
40/40 [==============================] - 0s 11ms/step - loss: 0.6771 - accuracy: 0.6156 - val_loss: 0.6697 - val_accuracy: 0.6550
Epoch 16/20
40/40 [==============================] - 0s 11ms/step - loss: 0.6763 - accuracy: 0.6156 - val_loss: 0.6684 - val_accuracy: 0.6550
Epoch 17/20
40/40 [==============================] - 0s 12ms/step - loss: 0.6755 - accuracy: 0.6156 - val_loss: 0.6672 - val_accuracy: 0.6550
Epoch 18/20
40/40 [==============================] - 0s 11ms/step - loss: 0.6747 - accuracy: 0.6156 - val_loss: 0.6660 - val_accuracy: 0.6550
Epoch 19/20
40/40 [==============================] - 0s 9ms/step - loss: 0.6740 - accuracy: 0.6156 - val_loss: 0.6649 - val_accuracy: 0.6550
Epoch 20/20
40/40 [==============================] - 0s 10ms/step - loss: 0.6734 - accuracy: 0.6156 - val_loss: 0.6639 - val_accuracy: 0.6550

In [ ]:
import random
import numpy as np

rand = random.randint(0,x_test.shape[0])
subject = x_test[rand]
subject = np.expand_dims(subject,axis=0)
prediction = model.predict(subject)
print("Predicted = "+str(round(prediction[0][0]))+"\n"+"actual = "+str(y_test[rand]))

Predicted = 1
actual = 1